export const box: string;
export const active: string;
export const Popover: string;
export const popover: string;
export const flexCenter: string;
export const textBox: string;
export const imgBox: string;
export const backImg: string;
export const img: string;
